travis:
  secure:
    BINSTAR_TOKEN: UsVZbaMDLsvqwLjvDkUK4IsAF5zx3VhCQG74koxOIqb2MbdOxp3VEM/qk4xzcX2luuGRi38npgVeJKNGA49ZtaWmIhgKO3l1pcRaNlecO/o98NpmutpjDxEDjPblzCqZ6xgorkSITpMJmnCPxpsVXfx6sLm+Ia2jFXGuo/w+9K7f3iLWnIYgdwoeORxenjFHxso8/y2rOmxBoJSOu6ZcCABvhZYY3qPI7TcsrSSEj+HMVHI8S5qButSowNn2Uzj0a7ocZPazmrMB0WSe1aj+43EeDD2lesR4M/XmyEj5ATOvqdX63oDlQ/fIxvadvY9A7XmGA26KQ7UYlYJCoZuxVdTlr4c3/2khhgAFLSJvzeTmPscD7gUpuS+VV+cUMgLI3VIq49UJQlQRA+dKqdXwCdauwWsnq8ACgKKDgm3tWLSFeX6MJqpNl+mpMKU5fjnOTvgFnVYbGyPyTnOWmuKMz4N6b4vyld1hXfSAArhA7xQyfm1uU9lCFgqRkFFLCuPMGLz8VWmXjIm3uYI4KnJLm+JnD/KqCUAaxQqffKEVFGOQHDEIWi5wu8FCjhdYhQ4dPUMX5pnFF6/CzsAw69obeoZtQeZuqP5CClLt+dvjazECTnn73H9NQvZ3krsM6N0f8ltc0YdCFCiCEtxhhu/VovRfRWrx3zA0Iyj3vIxVjuo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
